jenkins:
  systemMessage: "Configured automatically with JCasC plugin\n\n"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  labelString: flyweight
  numExecutors: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 2
  nodes:
  - permanent:
      labelString: "linux immutable docker x86_64"
      launcher:
        jnlp:
          workDirSettings:
            disabled: true
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
            workDirPath: "/tmp"
      name: "local"
      numExecutors: 2
      remoteFS: "/tmp"
      retentionStrategy: "always"
      
unclassified:
  location:
    adminAddress: robots@elastic.co
    url: http://localhost:8080/
  gitscm:
    globalConfigName: username
    globalConfigEmail: username@example.com

jobs:
  - file: "/Jenkinsfile.dsl"
