# This workflow build a Docker container with buildx.
name: Docker build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REPOSITORY: ghcr.io
      NAME: ${{ github.repository }}
      DEBIAN: 10
      BUILDX: 1 
    steps:
      - uses: actions/checkout@v3
        with:
          repository: elastic/golang-crossbuild
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - run: make -C go/base build