

# This workflow shows how to launch a custom runner in GitHub Actions and use it
name: Test gce-github-runner

permissions:
  contents: read
  id-token: write

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/844024446343/locations/global/workloadIdentityPools/github-action-identity-pool/providers/github-actions-oidc-token
  SERVICE_ACCOUNT: github-actions-vms@github-actions-356108.iam.gserviceaccount.com
  CLOUDSDK_PROJECT: github-actions-356108

on:
  workflow_dispatch:

jobs:
  create-runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@535b7c755131a1ab32ab2388bf907c716932376a
        with:
          token: ${{ secrets.PAT  }}
          project_id: ${{ env.CLOUDSDK_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          #  gcloud compute images list
          image_family: debian-11
          image_project: debian-cloud 
          machine_zone: us-central1-a
          machine-type: e2-micro 


  test:
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - run: |
          echo "This runs on the GCE runner VM"
          uname -a
      - uses: related-sciences/gce-github-runner@535b7c755131a1ab32ab2388bf907c716932376a
        with:
          command: stop
        if: always()