# This workflow to run Jenkins in a GitHub Action.
name: Jenkins running as a service

on:
  workflow_dispatch:

jobs:
  jenkins:
    services:
      jenkins:
        image: ghcr.io/kuisathaverat/jenkins:latest
        ports:
          - 8080:8080
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        volumes:
          - ./.github/docker/jenkins/Jenkinsfile.dsl:/Jenkinsfile.dsl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          JENKINS_URL="http://localhost:8080"
          curl -sSO http://localhost:8080/jnlpJars/jenkins-cli.jar
          java -jar jenkins-cli.jar -s "${JENKINS_URL}/" -webSocket build test