# This workflow to run Jenkins in a GitHub Action.
name: Jenkins running as a service

on:
  workflow_dispatch:

jobs:
  jenkins:
    services:
      jenkins:
        image: ghcr.io/kuisathaverat/jenkins:latest
        ports:
          - 8080
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
        # volumes:
        #   - full path/.github/docker/jenkins/Jenkinsfile.dsl:/Jenkinsfile.dsl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          PORT=${{ job.services.jenkins.ports['8080'] }}
          JENKINS_URL="http://127.0.0.1:${PORT}"
          curl -sSO --connect-timeout 10 --retry 30 --retry-delay 10 "${JENKINS_URL}/jnlpJars/jenkins-cli.jar"
          java -jar jenkins-cli.jar -s "${JENKINS_URL}/" -webSocket build test
          sleep 20
          docker logs $(docker ps -q  --filter ancestor=jenkins)