---
# Workflow to test check_suite event
name: On check_suite dummy
on:
  check_suite:
    types: [completed]

permissions:
    contents: read

jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"