---
# Workflow to test status event
name: On status dummy
on:
  status:

permissions:
    contents: read

jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"