---
# Workflow to test status and check_suite event
name: On status and check_suite dummy
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  status: {}

permissions:
  contents: read

jobs:
  on-push-dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: echo "This is a dummy step"
