# This workflow shows how to use OpenID Vault tokens.
name: OpenID Vault integration

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  secret01:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          secrets: |
            foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
  secret02:
    if: ${{ always() }}
    needs: secret01
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          secrets: |
            /foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
  secret03:
    if: ${{ always() }}
    needs: secret02
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          secrets: |
            cubbyhole/foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
  secret04:
    if: ${{ always() }}
    needs: secret03
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          secrets: |
            /cubbyhole/foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
  secret05:
    if: ${{ always() }}
    needs: secret04
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          secrets: |
            secrets/cubbyhole/foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
