# This workflow shows how to use OpenID tokens.
name: OpenID token

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.8.0'
        with:
            create_credentials_file: 'true'
            workload_identity_provider: 'projects/844024446343/locations/global/workloadIdentityPools/github-action-identity-pool/providers/github-actions-oidc-token'
            service_account: 'github-actions-tokens-generato@github-actions-356108.iam.gserviceaccount.com'
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          ls -la  ${{ steps.auth.outputs.credentials_file_path }}
          cat ${{ steps.auth.outputs.credentials_file_path }}
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list