# This workflow shows how to use OpenID Vault tokens.
name: OpenID Vault integration

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  secret01:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://104.155.175.88.ip.es.io:8200
          role: githubactions
          method: jwt
          jwtGithubAudience: https://github.com/kuisathaverat
          #jwtTtl: 30
          # kv v2 is <engine>/data/<path>
          secrets: |
            secrets/data/bar/foo value | VALUE_ENV_VAR
      - name: Use secret from Vault
        run: |
          echo "${VALUE_ENV_VAR}"
