# This workflow shows how to use OpenID tokens.
name: OpenID token

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.8.0'
        with:
            create_credentials_file: 'true'
            workload_identity_provider: 'projects/844024446343/locations/global/workloadIdentityPools/github-action-identity-pool/providers/github-actions-oidc-token'
            service_account: 'github-actions-tokens-generato@github-actions-356108.iam.gserviceaccount.com'
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud services list
          gcloud compute instances create instance-1 \
            --project=github-actions-356108 \
            --zone=us-central1-a \
            --machine-type=e2-micro \
            --network-interface=network-tier=PREMIUM,subnet=default \
            --maintenance-policy=MIGRATE 
        # --provisioning-model=STANDARD 
        # --service-account=844024446343-compute@developer.gserviceaccount.com \
        # --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
        # --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-11-bullseye-v20220621,mode=rw,size=10,type=projects/github-actions-356108/zones/us-central1-a/diskTypes/pd-balanced \
        # --no-shielded-secure-boot \
        # --shielded-vtpm \
        # --shielded-integrity-monitoring \
        # --reservation-affinity=any
#                    gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
