# This workflow test the reuse of workflows.
# this workflow is a reusable workflow
# see https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: reusing workflows called

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envGhToken:
        required: true
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.reusable_workflow_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.reusable_workflow_job.outputs.output2 }}
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - run: |
          echo "username: ${{ inputs.username }}"
          echo "token: ${{ secrets.envGhToken }}"
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"