# This workflow to execute a Python in all runner types
name: runners sample

on:
  workflow_dispatch:

jobs: 
  build:
    strategy:
      matrix:
        os:
          [
            windows-2022,
            windows-2019,
            ubuntu-22.04,
            ubuntu-20.04,
            ubuntu-18.04,
            macos-12,
            macos-11,
            macos-10.15
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Running on ${{ matrix.os }}
        shell: python
        run: |
          import platform
          import sys

          def linux_distribution():
            try:
              return platform.linux_distribution()
            except:
              return "N/A"

          def dist():
            try:
              return platform.dist()
            except:
              return "N/A"

          print("""Python version: %s
            dist: %s
            linux_distribution: %s
            system: %s
            machine: %s
            platform: %s
            uname: %s
            version: %s
            mac_ver: %s
            """ % (
            sys.version.split('\n'),
            str(dist()),
            linux_distribution(),
            platform.system(),
            platform.machine(),
            platform.platform(),
            platform.uname(),
            platform.version(),
            platform.mac_ver(),
          ))
