# This workflow test a custom action.
name: Test the get-runner-token actions.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: get_runner_token_docker
        uses: .github/actions/get-runner-token-docker
        with:
          pat: ${{ secrets.PAT }}
          reposiroty: ${{ github.repository }}
      - name: Try to leak a secret
        run: |
          python -c "print(' '.join('${{ steps.get_runner_token_docker.token }}'))"