# This workflow test a custom action.
name: Test the get-runner-token actions.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      DOCKER_IMAGE: ${{ github.actor }}/get-runner-token-docker
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .github/actions/get-runner-token
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.DOCKER_IMAGE }}
          labels: ${{ steps.meta.outputs.labels }}

  run_action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: get_runner_token_docker
        uses: ghcr.io/${{ github.actor }}/get-runner-token-docker:latest
        with:
          pat: ${{ secrets.PAT }}
          reposiroty: ${{ github.repository }}
      - name: Try to leak a secret
        run: |
          python -c "print(' '.join('${{ steps.get_runner_token_docker.token }}'))"